### ISSUE TITLE
Autoprefixer command not appearing

### ISSUE THREAD

**Issue by smlombardi** [sindresorhus/atom-autoprefixer#12]
I am using Atom .174 and AP 2.2.0 for Atom.

1. Create a simple CSS file
2. Bring up the command palette, type auto... no autoprefixer anywhere.

Happens with every file I have tried, simple to complex, with selection and without.

**Comment by smlombardi** [comment]
Further experimenting shows when I install Autoprefixer, I get a ".bin" package in my package list.

See https://discuss.atom.io/t/whats-this-bin-package/14355/3

**Comment by sindresorhus** [comment]
It shows up fine for me with the same Atom version. Maybe install failed somehow. Try reinstalling.

If it still doesn't work. Open an issue on Atom.
