### ISSUE TITLE
Command appearing with SCSS

### ISSUE THREAD

**Issue by LaurentTreguier** [sindresorhus/atom-autoprefixer#13]
I saw in other issues that SCSS isn't supported by autoprefixer. However, when opening both a CSS and a SCSS file in Atom, the `Autoprefix` command appears in the command palette because of the CSS file, but I can use it on the SCSS file too. And it seems to work perfectly from what I saw.

**Comment by kevva** [comment]
It's not locked to only CSS files but it's not guaranteed to work in Sass or Less etc.
