### ISSUE TITLE
Autoprefix on keypressed

### ISSUE THREAD

**Issue by jsncrdnl** [sindresorhus/atom-autoprefixer#14]
Great plugin ! 
Just a little bored by the fact that I have to open a command palette then trigger the action of auto prefixer..

Couldn't it be possible to automatically prefix css when pressing "tab", "space", "enter" or "ctrl-s" ?

**Comment by sindresorhus** [comment]
Yes, I've been wanting that too, but for it not to be too annoying, I need to perfectly preserve the cursor position #8, which I haven't had the time to look into yet. PR welcome.

**Comment by brutalcrozt** [comment]
spotted
