### ISSUE TITLE
autoprefixer didn't work on my OS X

### ISSUE THREAD

**Issue by h3l** [sindresorhus/atom-autoprefixer#16]
look the gif

![bug](https://cloud.githubusercontent.com/assets/1664952/8405415/e781e1ec-1e86-11e5-9470-7403f2c84e6d.gif)

**Comment by sindresorhus** [comment]
Try another property. `box-sizing` doesn't need to be prefixed anymore. It only prefixes properties that needs to be prefixed in the browsers you've specified.

**Comment by h3l** [comment]
thank you very much, it's my fault.

**Comment by jobn123** [comment]
it works
