### ISSUE TITLE
Windows 8 bug.

### ISSUE THREAD

**Issue by villanuevapk** [sindresorhus/atom-autoprefixer#17]
![atom-prefixer-bug](https://cloud.githubusercontent.com/assets/4774295/8800423/30ad0f3a-2fe5-11e5-9a3c-a9a07f2615e7.png)

This is what appears when i tried to run the plugin.

1. It doesn't work in some of property
2. It doesn't prefix -moz-, -o- and -ms-

**Comment by sindresorhus** [comment]
It only prefixes what it need to prefix depending on the browsers you need to support. Please see the gad zillion existing issues about this.
