### ISSUE TITLE
running autoprefixer has no effect

### ISSUE THREAD

**Issue by BMOv2600** [sindresorhus/atom-autoprefixer#19]
Properties I've tried 

* order, 
* clip, 
* transition,
* display: flex

It doesn't generate any error messages. It just leaves the code looking like it did prior to shift+cmd+P, "autoprefixer," enter.

Running OSX 10.10.4. Atom 1.0.5. atom-autoprefixer 2.2.4.

Probably something wrong with my config (below).

```
"*":
  editor:
    invisibles:
      eol: "!"
    fontSize: 15
    softWrapAtPreferredLineLength: true
    softWrap: true
  core:
    themes: [
      "one-dark-ui"
      "zenburn"
    ]
    disabledPackages: [
      "webbox-color"
      "csscomb"
      "css-comb"
      "linter-csslint"
      "gulp-helper"
      "gulp-snippets"
    ]
    projectHome: "~/app/BMO"
    audioBeep: false
    ignoredNames: [
      ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "Thumbs.db"
      ".codekit-cache"
      "bower_components"
      "node_modules"
    ]
  welcome:
    showOnStartup: false
  linter:
    lintOnFly: true
    showErrorPanel: false
  "webbox-color":
    fillColorAsBackground: false
  "white-cursor":
    darkThemes: [
      "zenburn"
    ]
  pigments:
    markerType: "underline"
  "atom-css-comb":
    projectConfigs: ".csscomb.json"
    readyMadeConfigs: "csscomb"
"linter-csslint":
  csslintExecutablePath: "/usr/local/bin/csslint-cli"
```

**Comment by sindresorhus** [comment]
Works for me with latest Atom and Autoprefixer. Can you try reinstalling the plugin?

**Comment by BMOv2600** [comment]
That was the last thing I did before posting this issue, but reinstalling again seems to have fixed it.

The package now adds empty lines between the prefixed rules though. Is that the default behavior? 

Looks like there is just a new line for each prefix on the readme.md demo.
