### ISSUE TITLE
auto running

### ISSUE THREAD

**Issue by robsonsobral** [sindresorhus/atom-autoprefixer#23]
Hi!

Thank you for the addon.

Is it possible to run it automatically on a closed file? I'm thinking about the ones generated by preprocessors. Something like Sass [AutoCompile](https://github.com/armin-pfaeffle/sass-autocompile) does.

Thank you for your attention.

**Comment by sindresorhus** [comment]
I would be open to a pull request that implemented a `Format On Save` option, if that's what you're asking for.

See: https://github.com/sindresorhus/atom-esformatter/blob/3b020123faad0dc96cb0bc716656a680472852d5/index.js#L44-L60

**Comment by robsonsobral** [comment]
Almost. In the case I'm thinking about, two options:

- when saving an `.scss`, the plugin need to wait until SASS saves the `css`, then open it and run the prefixing;
- or the plugin needs to watch the file system and detect when the `css` changes;

But maybe this is too complex, too out of scope for your addon.

**Comment by sindresorhus** [comment]
Definitely out of the scope for this plugin, and IMHO out of scope for an editor plugin. That's something that should be done in a build system.

I'm sure there's a build system type plugin for Atom. Just set it up to run the `atom-workspace:autoprefixer` command on changes. See Atom docs for how commands work.

**Comment by robsonsobral** [comment]
Thank you, @sindresorhus !
