### ISSUE TITLE
`Autoprefix On Save` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-autoprefixer#24]
When enabled, runs autoprefix on save.

See: https://github.com/sindresorhus/atom-esformatter/blob/3b020123faad0dc96cb0bc716656a680472852d5/index.js#L44-L60

Help welcome :)

**Comment by tobiasger** [comment]
If I'm using SASS/SCSS, will this be executed on the compiled CSS file or the SASS/SCSS file itself?

**Comment by sindresorhus** [comment]
It will be run on the open file, whatever that is.
