### ISSUE TITLE
i can't get it to work 

### ISSUE THREAD

**Issue by sameh0** [sindresorhus/atom-autoprefixer#26]
i've tried many times with CSS and HTML files and doesn't work 
it either returns 
``Cannot read property '0' of undefined
`or do nothing . 
using ATOM 1.4.3

**Comment by sindresorhus** [comment]
When it does nothing might just be a case of https://github.com/sindresorhus/atom-autoprefixer/issues/16. This is not a very actionable issue though. Please try next time.
