### ISSUE TITLE
Support for sass

### ISSUE THREAD

**Issue by chrised123** [sindresorhus/atom-autoprefixer#27]
Hi @sindresorhus 

Great job with the package. I am wondering whether you have plans to support SASS?

Thanks again.

**Comment by sindresorhus** [comment]
Do you mean SASS or SCSS? SCSS is already supported. As for SASS, yes, if someone makes a parser like https://github.com/postcss/postcss-scss.

**Comment by kunokdev** [comment]
Sass syntax the one without semicolons

**Comment by sindresorhus** [comment]
That would be a feature request for PostCSS. They would have to provide a parser like https://github.com/postcss/postcss-scss for SASS.
