### ISSUE TITLE
Converting comments

### ISSUE THREAD

**Issue by jacobmischka** [sindresorhus/atom-autoprefixer#30]
Is it possible to stop this package from converting my SCSS `//` comments to regular CSS `/* */` comments? It's not necessarily a huge deal, but I would like to keep my SCSS comments from appearing in my output CSS.

Thanks!

**Comment by sindresorhus** [comment]
Can you open an issue on the parser: https://github.com/postcss/postcss-scss Not much I can do about it here.

**Comment by jacobmischka** [comment]
Oh yeah you're right opening it here didn't really make much sense did it. 

Thanks!

**Comment by jacobmischka** [comment]
Well actually, it seems they're left in when I use autoprefixer from postcss directly. When I have some time I'll try to figure out why.

**Comment by solid-pixel** [comment]
@jacobmischka hi, have you been able to find a solution? It's rather annoying especially when using CTRL+/ as you can't remove the comment via hotkey anymore.

**Comment by jacobmischka** [comment]
Unfortunately no, sorry. I've started using autoprefixer in my build step instead of in atom.

**Comment by solid-pixel** [comment]
that's a shame :( thanks a lot for coming back to me!
