### ISSUE TITLE
Add saving on load to a different file

### ISSUE THREAD

**Issue by CallMeMantas** [sindresorhus/atom-autoprefixer#34]
I use [the sass-autocompile](https://atom.io/packages/sass-autocompile) package and really don’t want to complicate things too much in my workflow and let Atom do all the work. The way that package compiles and saves files is by creating a new file called `all.min.css` from `all.scss`. If this package could do the same, that’d be just *wonderful*. Lovely. This should fix [the “Converting comments” issue](https://github.com/sindresorhus/atom-autoprefixer/issues/30) that I’m dealing with as well.

**Comment by sindresorhus** [comment]
Sorry, that's outside the scope of this plugin and better done in a build-step.
