### ISSUE TITLE
TextEditor.get is deprecated.

### ISSUE THREAD

**Issue by uncleserb** [sindresorhus/atom-autoprefixer#35]
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.

```
TextEditor.get (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:101:14)
<unknown> (/Users/paul/.atom/packages/autoprefixer/index.js:45:76)
```

**Comment by jadchaar** [comment]
Adding onto this issue, here is the error in its fullest form in Atom:

<img width="1084" alt="screen shot 2017-01-14 at 2 59 36 pm" src="https://cloud.githubusercontent.com/assets/7388203/21957688/38bd4da8-da6a-11e6-832e-ea6e3c52b79b.png">

**Comment by anthony-pinskey** [comment]
I am getting the same error. Can anyone confirm this will be addressed soon?
