### ISSUE TITLE
sass-autocompile header issue

### ISSUE THREAD

**Issue by doar2016** [sindresorhus/atom-autoprefixer#38]
Auto-prefixer  automatically changes the following...
//compileCompressed: ../css/style.min.css

to a CSS comment
/*compileCompressed: ../css/flex.min.css*/

Unfortunately, this stops the desired functionality, which is to compile the SCSS file to a specific CSS file.

**Comment by sindresorhus** [comment]
Open an issue on https://github.com/postcss/postcss-scss instead. That's the parser used here.
