### ISSUE TITLE
Delete flex box webkit prefix and break my code

### ISSUE THREAD

**Issue by pingshunhuangalex** [sindresorhus/atom-autoprefixer#39]
I spent a couple of hours trying to figure out why my code suddenly broke, and it turns out that `autoprefixer` deletes all my `display: -webkit-flex;`, hence causing the issue.

Could you please go ahead and fix this? I also had a feeling that many prefixer may be out of date since this  package hasn't been updated for a long time. Thanks.

**Comment by sindresorhus** [comment]
It's up to you to specify what browsers you want to support in the `browsers` option. Autoprefixer removes unnecessary prefixes according to this config.

> I also had a feeling that many prefixer may be out of date since this package hasn't been updated for a long time.

Reinstall this plugin and you'll get the latest Autoprefixer.

**Comment by pingshunhuangalex** [comment]
Hi @sindresorhus 

Thanks for the reply.

I'm using the default settings which should support `the last 2 versions for each major browser.` I also tried `last 2 Chrome versions` and `> 5%`, but not luck. `display: -webkit-flex;` will always be regarded as redundant and deleted.

I'm using the latest Chrome 57. If `display: -webkit-flex;` is not necessary, it shouldn't break my code in the first place. I'm open to any browser options that can resolve this without turning off the `remove unnecessary prefix` option. Thanks.

**Comment by sindresorhus** [comment]
Try asking in https://gitter.im/postcss/postcss

**Comment by pingshunhuangalex** [comment]
Thanks @sindresorhus 
The way you answered my question makes me realise that if `display: -webkit-flex;` is supported by Chrome long time ago, it means this should be written as `display: flex;` which reders `-webkit-flex;` unnecessary. Thanks.
