### ISSUE TITLE
Chain autoprefixer with sass-autocompile

### ISSUE THREAD

**Issue by richardbushell** [sindresorhus/atom-autoprefixer#40]
It would be fantastic if autoprefixer could be chained with sass-autocompile
https://github.com/armin-pfaeffle/sass-autocompile/issues/34

Any chance of collaborating the two packages to make this happen?

**Comment by sindresorhus** [comment]
This plugin already supports SCSS.

**Comment by richardbushell** [comment]
Apologies, I think you mis-understood my question. I know that autoprefixer supports SCSS.
sass-autocompile compiles SCSS into CSS, with current options to compress (minify) it too. I was suggesting that autoprefixer could be an additional option to sass-autocompile, so that it could compile the SCSS to a minified CSS file and also autoprefix it too as an additional option. It was a feature request, as BOTH processes are required for most people.
