### ISSUE TITLE
-moz prefix missing

### ISSUE THREAD

**Issue by Krishtof** [sindresorhus/atom-autoprefixer#43]
I tried to use the autoprefixer but it won't add the -moz prefixes to the css code.. For example  for box -sizing this is what I get if I run the autoprefixer:

.item {
    position: absolute;
  margin-top: 120px;
  float: right;
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
  display: block;
  right: 5%;
  }

**Comment by sindresorhus** [comment]
Same as https://github.com/sindresorhus/atom-autoprefixer/issues/39#issuecomment-286360562.
