### ISSUE TITLE
Incorrect handling comments in .less files (version 3.7.1)

### ISSUE THREAD

**Issue by dtsdev** [sindresorhus/atom-autoprefixer#44]
When autoprefixer applied to the less file, it destroys the structure of the less-related first-line comment used as a command line for less compiler. It places semicolons after commas and as a result line like this: 

`// out: ../../css/styles.min.css, sourcemap: false, compress: true`

is changed to

`// out: ../../css/styles.min.css,; sourcemap: false,; compress: true`

making it incorrectly processed by the less compiler as no `sourcemap` nor `compress` works anymore.

**Comment by sindresorhus** [comment]
Less is not supported. See the readme.
