### ISSUE TITLE
Need config flag to disable SCSS autoprefixing

### ISSUE THREAD

**Issue by janscarton** [sindresorhus/atom-autoprefixer#48]
There really needs to be a setting to disable SCSS autoprefixing. I want vendor prefixes in my compiled CSS, but NOT in my SCSS.

This seems like it would be the standard use case. Why would you want vendor prefixes in your preprocessor language? I thought the whole point of autoprefixer is so the author doesn't have to deal with vendor prefixes!

**Comment by p0lm** [comment]
I strongly agree. I strongly suggest to include the option to watch a (set of) css files that will be prefixed on change. This allows this package to play nicely together with [atom-sass](https://github.com/rehrumesh/atom-sass).

**Comment by sindresorhus** [comment]
This plugin is intended for use when you don't have a build system set up and just want to auto-prefix the source file. I don't intend to turn this into a build system thingy. There are better options if you need that.
