### ISSUE TITLE
Add support for cascaded output

### ISSUE THREAD

**Issue by fnando** [sindresorhus/atom-autoprefixer#5]
Would be nice to have a checkbox for enabling `cascade: true` option.

**Comment by BMOv2600** [comment]
So is this issue solved? Because I get the same result whether 'Cascade prefixes' is enabled or disabled. Is that just because of Autoprefixer?

Config says it's set to default when I get the below result:

**test.css**

`div 
	{
		display: -webkit-box;display: -webkit-flex;display: -ms-flexbox;display: flex;
	}
`

Is this still because of Autoprefixer?
