### ISSUE TITLE
Autoprefixer changed "height: 0;" to "height: ;"

### ISSUE THREAD

**Issue by Azragh** [sindresorhus/atom-autoprefixer#50]
As I was working on a "fixed aspect ratio layout" for WordPress gallery, I found this little nasty bug:

When I write this (in SCSS):
```
.gallery-icon {
  // 16:10:
  height: 0;
  line-height: 0;
  padding-top: 100% / 16 * 10;
}
```
After runnin' Autoprefixer the "0" after the inline comment gets removed! When I omit the ":", Autoprefixer adds ";" after the inline comment.. ;)

**Comment by sindresorhus** [comment]
Can you move this issue to the SCSS parser: https://github.com/postcss/postcss-scss ;)
