### ISSUE TITLE
Multi browser

### ISSUE THREAD

**Issue by RahulDey12** [sindresorhus/atom-autoprefixer#51]
Hi there, 
    I recently installed autoprfixer in atom an I can not make multiple browser configuration please help me it only giving webkit

**Comment by piilzner** [comment]
Hey!
I experience the same thing as @RahulDey12 . It only makes webkit prefix.

**Comment by branditodesign** [comment]
You guys have edited your Autoprefixer settings and included other browsers in your configuration right?
