### ISSUE TITLE
No ::placeholder pseudo element vendor prefix for Mozilla

### ISSUE THREAD

**Issue by yialo** [sindresorhus/atom-autoprefixer#52]
I use ::placeholder preudo element for placeholder stylizing in input fields and textareas. When I use autoprefixer it adds these:
::-webkit-input-placeholder
::-ms-input-placeholder
:-ms-input-placeholder

But it does not add these prefixes:
::-moz-placeholder
:-moz-placeholder

And Firefox browser does not add styles to placeholder without ::-moz-placeholder/:-moz-placeholder pseudo elements prefixes.

**Comment by sindresorhus** [comment]
The styles it adds depends on what browsers and browser versions you target in the browser setting.
