### ISSUE TITLE
Autoprefixer adding commas in places they shouldn't be (in inline svg's used as background images)

### ISSUE THREAD

**Issue by branditodesign** [sindresorhus/atom-autoprefixer#55]
Autoprefix this:
`background-image: url("data:image/svg+xml,<svg xmlns:dc='http://purl.org/dc/elements/1.1/' xmlns:cc='http://creativecommons.org/ns%23' xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns%23' xmlns:svg='http://www.w3.org/2000/svg' xmlns='http://www.w3.org/2000/svg' xml:space='preserve' style=';-webkit-transform: rotate(25deg) scaleX(-1);-o-transform: rotate(25deg) scaleX(-1);-moz-transform: rotate(25deg) scaleX(-1);-ms-transform: rotate(-51deg) scaleX(-1);transform: rotate(-51deg) scaleX(-1);fill:%23a13838;' enable-background='new 0 0 595.28 841.89' viewBox='0 0 776.09175 693.66538' height='693.66541' width='776.0918' y='0px' x='0px' id='Layer_1' version='1.1'><metadata id='metadata11'><rdf:RDF><cc:Work rdf:about=''><dc:format>image/svg+xml</dc:format><dc:type rdf:resource='http://purl.org/dc/dcmitype/StillImage'/><dc:title/></cc:Work></rdf:RDF></metadata><defs id='defs9'/><g transform='matrix(2.7190747,0,0,3.1037754,-326.9763,-1172.9045)' id='g3'><path style=';clip-rule:evenodd;fill-rule:evenodd' id='path5' d='m 130.838,381.118 c 1.125,28.749 5.277,54.82 12.695,78.018 7.205,22.53 18.847,40.222 36.812,53.747 52.018,39.16 153.369,16.572 153.369,16.572 l -4.632,-32.843 72.918,42.778 -58.597,58.775 -3.85,-27.303 c 0,0 -100.347,18.529 -163.905,-34.881 -37.659,-31.646 -53.293,-84.021 -51.593,-153.962 0.266,-0.247 4.728,-0.908 6.783,-0.901 z'/></g></svg>");`
with 'last 999 versions' as your settings.
It keeps adding a comma in a few of the xmlns attributes before the 'http' which breaks the SVG entirely.

**Comment by sindresorhus** [comment]
Issues with the output should be opened on the Autoprefixer repo: https://github.com/postcss/autoprefixer
