### ISSUE TITLE
Add option to only add prefixes to the .css output when working with .scss/.sass?

### ISSUE THREAD

**Issue by branditodesign** [sindresorhus/atom-autoprefixer#56]
It'd be great if the prefixes were only added to the .css file after/upon save as it would keep the .scss file about half the length and maintain readability. (lots 'o' prefixes with last 999 versions)

**Comment by sindresorhus** [comment]
If you use Sass, you already have a build system, so it would be better to just integrate Autoprefixer into that than using this plugin.
