### ISSUE TITLE
Can autoprefixer be updated in real time

### ISSUE THREAD

**Issue by linjialiang** [sindresorhus/atom-autoprefixer#60]
Can autoprefixer be updated in real time

**Comment by sindresorhus** [comment]
Would be nice, but I don't think it's feasible. We just send the whole file to Autoprefixer and it sends the whole prefixed file back. This means we'll have to do some smart diffing to preserve the cursor.

This is blocked by https://github.com/sindresorhus/atom-autoprefixer/issues/8 and https://github.com/sindresorhus/atom-autoprefixer/issues/47.

**Comment by linjialiang** [comment]
> 您可能误解了，我的意思是这个更新 [`postcss-autoprefixer`](https://github.com/postcss/autoprefixer)

If I can't sync with this, does it mean that after a while I need to reinstall the plug-in to make sure `autoprefixer` is up to date

**Comment by sindresorhus** [comment]
@linjialiang Ah ok. Yes, dependencies are not updated unless you reinstall the plugin, or there's an atom-autprefixer update. This is a limitation on how the Atom plugin system works and not something I can fix. You should open an issue on Atom requesting to get a setting for plugins to get reinstalled once in awhile to get fresh dependencies.

**Comment by linjialiang** [comment]
Thank you for your reply
