### ISSUE TITLE
add dev guide

### ISSUE THREAD

**Issue by gurungrahul2** [sindresorhus/atom-autoprefixer#63]
I would love to see a guide like in other repos , a brief text on how to get started hacking this really helps beginners. Just steps on how to manually test it from repo and how do you develop it, is there something similar like we had `astexplorer` site?

**Comment by sindresorhus** [comment]
I think this is better covered by the Atom docs: https://www.google.com/search?q=atom+plugin+guide&oq=atom+plugin+guide&aqs=chrome..69i57j0l3.2493j0j1&sourceid=chrome&ie=UTF-8 `eslint-plugin-unicorn` has special documentation, as the official ones are not that great.
