### ISSUE TITLE
Doesn't seem to work with embedded CSS files?

### ISSUE THREAD

**Issue by Ridiculicious** [sindresorhus/atom-autoprefixer#69]
1. Does this work with embedded CSS? If so how do you prefix the styles in the HTML?

2. In the CSS files, no prefixing occurs or an error shows up. Steps: 1. select all code 2. pull up command pallet, 3. Select auto prefix. 4. Result = nothing.

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
