### ISSUE TITLE
how to use auto prefix for grid?

### ISSUE THREAD

**Issue by forgethen** [sindresorhus/atom-autoprefixer#73]
Sorry for the fact that perhaps such a question already existed, but how to use the auto prefixer for grid elements?

  eg:

a {
   display: grid;
   grid-template-columns: 1fr 100px;
   grid-template-rows: 1fr;
   grid-gap: 15px;
}

I would like to see after starting the auto-prefixer:

a {
display: -ms-grid;
display: grid;
-ms-grid-columns: 1fr 15px 100px;
grid-template-columns: 1fr 100px;
-ms-grid-rows: 1fr;
grid-template-rows: 1fr;
grid-gap: 15px;
} a> *: nth-child (1) {
-ms-grid-row: 1;
-ms-grid-column: 1;
} a> *: nth-child (2) {
-ms-grid-row: 1;
-ms-grid-column: 3;
}

**Comment by forgethen** [comment]
Having tried to change the index. of the package, the desired result appeared, but not fully and with some errors. inside function on line 56 added

grid: {
title: 'Grid Prefixes',
type: 'boolean',
default: true
},

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
