### ISSUE TITLE
Is this tool deprecated?

### ISSUE THREAD

**Issue by ZNUfisk** [sindresorhus/atom-autoprefixer#77]
Tried to use the autoprefixer as per: 
https://autoprefixer.github.io/

inside a separate css-file (test.css)

Code below:
.example {
    display: grid;
    transition: all .5s;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
}

With this autoprefixer, for atom, run from the command, something happens; but the output is:

.example {
    display: grid;
    transition: all .5s;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    background: linear-gradient(to bottom, white, black);
}

Which does not correspond to the Autoprefixer output (which should be):

.example {
    display: -ms-grid;
    display: grid;
    -webkit-transition: all .5s;
    -o-transition: all .5s;
    transition: all .5s;
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    background: -webkit-gradient(linear, left top, left bottom, from(white), to(black));
    background: -o-linear-gradient(top, white, black);
    background: linear-gradient(to bottom, white, black);
}

Conclusion: Autoprefixer for Atom is (partially) deprecated/unusable in 2021.

**Comment by sindresorhus** [comment]
The prefix output depends on what browser targets you configure.

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
